//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "page_view_counter")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub path: String,
    pub times: i32,
    pub reaction0: i32,
    pub reaction1: i32,
    pub reaction2: i32,
    pub reaction3: i32,
    pub reaction4: i32,
    pub reaction5: i32,
    pub reaction6: i32,
    pub reaction7: i32,
    pub reaction8: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
