//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "comment_status")]
#[serde(rename_all = "snake_case")]
pub enum CommentStatus {
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "spam")]
    Spam,
    #[sea_orm(string_value = "waiting")]
    Waiting,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_gender")]
#[serde(rename_all = "snake_case")]
pub enum UserGender {
    #[sea_orm(string_value = "female")]
    Female,
    #[sea_orm(string_value = "male")]
    Male,
    #[sea_orm(string_value = "unknown")]
    Unknown,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_type")]
#[serde(rename_all = "snake_case")]
pub enum UserType {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "normal")]
    Normal,
}
