[web]
connect_info = true

[web.middlewares]
static = { enable = true, uri = "/static", path = "static", precompressed = true, fallback = "index.html" }

[mail]
host = "smtp.163.com"                                                      # SMTP mail server address,
port = 465                                                                 # SMTP server port number
secure = true                                                              # Response timeout, in milliseconds
auth = { user = "hff1996723@163.com", password = "${MAIL_AUTH_PASSWORD}" } # Authentication information
stub = true

[email]
from = "hff1996723@163.com"

[sea-orm]
uri = "postgres://postgres:xudjf23adj213@localhost:5432/raline"

[sea-orm-web]
one_indexed = true

[redis]
uri = "redis://127.0.0.1/"

[raline]
site_url = "http://localhost:8080"
server_url = "http://localhost:8080"

[logger]
pretty_backtrace = false
